apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k8s-api-bench
  name: k8s-api-bench
  namespace: default
spec:
  serviceAccount: benchmarksuser
  containers:
  - image: quay.io/korvoj/k8s-api-bench:v1.0.0
    imagePullPolicy: Always
    name: k8s-api-bench
    resources: {}
    env:
      - name: ITERATIONS
        value: '5000'
      - name: CONCURRENCY
        value: '100'
      - name: REQUESTS_PER_SECOND
        value: '10'
  nodeSelector:
    kubernetes.io/hostname: l26-node03
  restartPolicy: Never